name: contact_card
description: A dart library to work with MeCard and vCard in their different versions. Create MeCard or vCard objects from text and vice versa.
version: 0.0.2
homepage: https://github.com/DamianAldair/contact_card
repository: https://github.com/DamianAldair/contact_card

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
